<a href="https://colab.research.google.com/github/jossxopa/store_ds/blob/main/Copia_di_Store_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [92]:
# 1. Clonamos el repositorio
! git clone https://github.com/alura-es-cursos/challenge1-data-science-latam.git

Cloning into 'challenge1-data-science-latam'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 10 (delta 3), reused 3 (delta 3), pack-reused 2 (from 1)
Receiving objects: 100% (10/10), 171.26 KiB | 1.36 MiB/s, done.
Resolving deltas: 100% (3/3), done.

In [93]:
# 2. Entramos a la carpeta del proyecto (Consejo de Oro)
%cd challenge1-data-science-latam

/content/challenge1-data-science-latam/challenge1-data-science-latam/challenge1-data-science-latam/challenge1-data-science-latam/challenge1-data-science-latam

In [94]:
# 3. Listamos los archivos para ver qué hay dentro
!ls

AluraStoreLatam.ipynb  base-de-datos-challenge1-latam

In [95]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

In [96]:
tienda4.shape

(2358, 12)

#**Ingreso total por tienda**

In [97]:
total_ganancia_por_tienda = {
    "tienda 1": tienda["Precio"].sum(),
    "tienda 2": tienda2["Precio"].sum(),
    "tienda 3": tienda3["Precio"].sum(),
    "tienda 4": tienda4["Precio"].sum()
}

for numero_de_tienda, total in total_ganancia_por_tienda.items(): #.item dice: oye no solo me des la llave pasame todo lo que hay ahí, o sea la operación matematica
  print(f'El ingreso total de la {numero_de_tienda} es de: ${total:,.2f}') #,.2f significa: Ponle comas para los miles y solo 2 decimales

El ingreso total de la tienda 1 es de: $1,150,880,400.00
El ingreso total de la tienda 2 es de: $1,116,343,500.00
El ingreso total de la tienda 3 es de: $1,098,019,600.00
El ingreso total de la tienda 4 es de: $1,038,375,700.00

# **1. Análisis de facturación**

#**2. Ventas por categoría**

In [98]:
# tienda.isnull().sum() comprobamos que no hay datos nulos.

cantidad_productos_vendidos = {
   "tienda 1": tienda['Categoría del Producto'].value_counts().head(3).reset_index(),
   "tienda 2":tienda2['Categoría del Producto'].value_counts().head(3).reset_index(),
   "tienda 3":tienda3['Categoría del Producto'].value_counts().head(3).reset_index(),
   "tienda 4":tienda4['Categoría del Producto'].value_counts().head(3).reset_index()
}

for nombre_tienda, cantidad_productos in cantidad_productos_vendidos.items():
  print(f'\n---Los 3 productos más vendidos en la {nombre_tienda} son:---')
  print(cantidad_productos)

---Los 3 productos más vendidos en la tienda 1 son:---
  Categoría del Producto  count
0                Muebles    465
1           Electrónicos    448
2               Juguetes    324

---Los 3 productos más vendidos en la tienda 2 son:---
  Categoría del Producto  count
0                Muebles    442
1           Electrónicos    422
2               Juguetes    313

---Los 3 productos más vendidos en la tienda 3 son:---
  Categoría del Producto  count
0                Muebles    499
1           Electrónicos    451
2               Juguetes    315

---Los 3 productos más vendidos en la tienda 4 son:---
  Categoría del Producto  count
0                Muebles    480
1           Electrónicos    451
2               Juguetes    338

#**3. Calificación promedio de la tienda**

In [119]:
promedio_calificacion = {
    "tienda 1": tienda.groupby("Categoría del Producto").agg({"Calificación": ['mean']}).round(2),
    "tienda 2": tienda2.groupby("Categoría del Producto").agg({"Calificación": ['mean']}).round(2),
    "tienda 3": tienda3.groupby("Categoría del Producto").agg({"Calificación": ['mean']}).round(2),
    "tienda 4": tienda4.groupby("Categoría del Producto").agg({"Calificación": ['mean']}).round(2)
}

for nombre_de_tienda, promedio_por_tienda in promedio_calificacion.items():
  print(f'\n --- La satisfacción del cliente en relación con los productos vendidos de la {nombre_de_tienda}: ')
  print(f'{promedio_por_tienda}')

 --- La satisfacción del cliente en relación con los productos vendidos de la tienda 1:
                        Calificación
                                mean
Categoría del Producto
Artículos para el hogar         3.75
Deportes y diversión            3.90
Electrodomésticos               4.03
Electrónicos                    4.00
Instrumentos musicales          4.05
Juguetes                        4.08
Libros                          3.98
Muebles                         3.95

 --- La satisfacción del cliente en relación con los productos vendidos de la tienda 2:
                        Calificación
                                mean
Categoría del Producto
Artículos para el hogar         4.07
Deportes y diversión            4.07
Electrodomésticos               4.07
Electrónicos                    3.97
Instrumentos musicales          4.04
Juguetes                        4.03
Libros                          3.95
Muebles                         4.09

 --- La satisfacción del cliente en relación con los productos vendidos de la tienda 3:
                        Calificación
                                mean
Categoría del Producto
Artículos para el hogar         4.07
Deportes y diversión            3.94
Electrodomésticos               4.01
Electrónicos                    3.99
Instrumentos musicales          4.01
Juguetes                        4.20
Libros                          4.05
Muebles                         4.10

 --- La satisfacción del cliente en relación con los productos vendidos de la tienda 4:
                        Calificación
                                mean
Categoría del Producto
Artículos para el hogar         4.01
Deportes y diversión            4.05
Electrodomésticos               3.93
Electrónicos                    4.01
Instrumentos musicales          3.91
Juguetes                        3.99
Libros                          4.04
Muebles                         4.00

#**4. Productos más y menos vendidos**

In [100]:
tienda.head(1)

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175

#**5. Envío promedio por tienda**